#!/bin/bash

output=$(pactl -f json list sinks | jq -r --arg s "$sink_name" '.[] | select(.name=="alsa_output.pci-0000_80_1f.3.analog-stereo") | .active_port') 
device="alsa_output.pci-0000_80_1f.3.analog-stereo"

if [[ $output == "analog-output-speaker" ]]; then
    pactl set-sink-port $device analog-output-headphones && notify-send "Audio switched to headphones"

elif [[ $output == "analog-output-headphones" ]]; then
    pactl set-sink-port $device analog-output-speaker && notify-send "Audio switched to speakers"

else
    notify-send "Audio switch failed"
fi
