#!/usr/bin/env bash

#Script written by BreadOnPenguins
#Modified by FluffyPuppyKasey

# Array of disks and matching icons
DISKS=("/" "/home")
ICONS=("󰣇 " " ")

# Define a file to save current disk and format, and initialize if not found
DISKS_FILE="/tmp/dwmblocks_disk_info"
[ -f "$DISKS_FILE" ] || echo "0 0" > "$DISKS_FILE"

# Read INDEX number and FORMAT number from the file
read INDEX FORMAT < "$DISKS_FILE"

# Set the current disk and icon per INDEX #
CURRENT_DISK="${DISKS[$INDEX]}"
ICON="${ICONS[$INDEX]}"

# Pull usage % and space remaining of that disk
# Could add more display formats here
PERCENT=$(df -h "$CURRENT_DISK" | awk 'NR==2 {print $5}')
SPACE=$(df -h "$CURRENT_DISK" | awk 'NR==2 {print $4}')

# If format is 0, display usage %, otherwise, space remaining
# Could instead use a case statement if more formats are added
[ "$FORMAT" -eq 0 ] && INFO="$PERCENT" || INFO="$SPACE"

# Send to bar
echo "$ICON$INFO"
